# Generated by Django 5.0.6 on 2024-06-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
