# Generated by Django 5.0.6 on 2024-06-02 11:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_rename_end_time_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=10),
        ),
    ]
