# Generated by Django 5.0.6 on 2024-06-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_remove_experience_responsibilities_responsibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibility',
            options={'verbose_name_plural': 'Responsibilities'},
        ),
    ]
