# Generated by Django 5.0.6 on 2024-06-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_alter_responsibility_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='experiences.experience'),
        ),
    ]
