# Generated by Django 5.0.6 on 2024-06-10 05:57

import cloudinary_storage.storage
import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('small_description', models.CharField(max_length=50)),
                ('description', tinymce.models.HTMLField()),
                ('technologies_used', models.CharField(blank=True, max_length=500)),
                ('project_type', models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('full-stack', 'full-stack')], max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('repository_url', models.URLField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='my-portfolio/projects/videos/')),
                ('conclusion', tinymce.models.HTMLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='my-portfolio/projects/images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
        ),
    ]
