# Generated by Django 5.0.6 on 2024-06-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('full-stack', 'full-stack')], default='backend', max_length=50),
            preserve_default=False,
        ),
    ]
