# Generated by Django 5.0.6 on 2024-06-04 07:49

import cloudinary_storage.storage
import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='my-portfolio/projects/videos/', validators=[portfolio.validators.validate_video_file_extension]),
        ),
    ]
