# Generated by Django 5.0.6 on 2024-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='conclusion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
