# Generated by Django 5.0.6 on 2024-06-07 07:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='conclusion',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
