# Generated by Django 5.0.6 on 2024-05-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skills_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
