# Generated by Django 5.0.6 on 2024-06-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('Programming Language', 'Programming Language'), ('Backend', 'Backend Technologies'), ('Frontend', 'Frontend Technologies'), ('DevOps & Deployment', 'DevOps and Deployment'), ('Messaging & Task Queues', 'Messaging and Task Queues'), ('Testing', 'Testing'), ('Version Control', 'Version Control'), ('Operating Systems', 'Operating Systems')], max_length=50),
        ),
    ]
